name: SSH Key Store Action
author: Ajit Singh Shekhawat
description: Save/ Update SSH private Key in a secret in the GitHub Actions API.
inputs:
  name:
    description: Name of the secret that you want to create/update
    required: true
  privatekey-file:
    description: name of ptivate key file
    required: true
  location:
    description: Name of a target GitHub repository or organization where secret will be created/updated
    required: false
  org-visibility:
    description: Visibility setting for organization secrets. Accepts `all`, `private` or a comma-seperated list of GitHub repository IDs
    required: false
    default: 'private'
  pa-token:
    description: Personal access token with permission to modify repository or organization secrets
    required: true
outputs:
  status:
    description: HTTP Status Code of the request against the GitHub API that created/updated the secret
runs:
  using: "node16"
  main: "dist/index.js"
